import type { ShowItem } from "@/lib/shows-recommendations-grok";

export const CURATED_SHOWS_VERSION = 7;

export const CURATED_SHOWS: ShowItem[] = [
  {
    title: "Severance",
    year: "2022",
    type: "show",
    description:
      "A surgical office experiment splits work memories from personal ones, turning every hallway into a quiet nightmare.",
    genre: "Sci-Fi Thriller",
    country: "USA",
    language: "English",
    streamingService: "Apple TV+",
    tmdbSearchTitle: "Severance",
    trailerSearchQuery: "Severance official trailer Apple TV",
    trailerVideoId: "xEQP4VVuyrY",
    mood: "suspenseful",
    posterUrl: "/media/shows/severance.jpg",
  },
  {
    title: "The Bear",
    year: "2022",
    type: "show",
    description:
      "A gifted chef tries to turn chaos into craft while every service threatens to boil over into panic and comedy.",
    genre: "Drama",
    country: "USA",
    language: "English",
    streamingService: "Hulu",
    tmdbSearchTitle: "The Bear",
    trailerSearchQuery: "The Bear official trailer FX",
    trailerVideoId: "vOyRo-Yjr2Q",
    mood: "funny",
    posterUrl: "/media/shows/the-bear.jpg",
  },
  {
    title: "Slow Horses",
    year: "2022",
    type: "show",
    description:
      "A washed-up MI5 team stumbles into deadly operations, balancing spycraft tension with witheringly dry humor.",
    genre: "Spy Thriller",
    country: "UK",
    language: "English",
    streamingService: "Apple TV+",
    tmdbSearchTitle: "Slow Horses",
    trailerSearchQuery: "Slow Horses official trailer Apple TV",
    trailerVideoId: "O9ZJChzPn0U",
    mood: "quirky",
    posterUrl: "/media/shows/slow-horses.jpg",
  },
  {
    title: "Dark",
    year: "2017",
    type: "show",
    description:
      "A missing child tears open a knot of family secrets, time travel, and dread in a small German town.",
    genre: "Sci-Fi Mystery",
    country: "Germany",
    language: "German",
    streamingService: "Netflix",
    tmdbSearchTitle: "Dark",
    trailerSearchQuery: "Dark official trailer Netflix",
    trailerVideoId: "cq2iTHoLrt0",
    mood: "gritty",
    posterUrl: "/media/shows/dark.jpg",
  },
  {
    title: "Mr. & Mrs. Smith",
    year: "2024",
    type: "show",
    description:
      "Two strangers fake a marriage for spy missions and wind up turning stylish chaos into chemistry.",
    genre: "Spy Comedy",
    country: "USA",
    language: "English",
    streamingService: "Prime Video",
    tmdbSearchTitle: "Mr. & Mrs. Smith",
    trailerSearchQuery: "Mr and Mrs Smith official trailer Prime Video",
    trailerVideoId: "AsaMWxppznk",
    mood: "fun",
    posterUrl: "/media/shows/mr-and-mrs-smith.jpg",
  },
];

export const CURATED_MOVIES: ShowItem[] = [
  {
    title: "Dune: Part Two",
    year: "2024",
    type: "movie",
    description:
      "Paul Atreides embraces prophecy, revenge, and all-out war on a desert world built for scale and dread.",
    genre: "Sci-Fi Epic",
    country: "USA",
    language: "English",
    streamingService: "Max",
    tmdbSearchTitle: "Dune: Part Two",
    trailerSearchQuery: "Dune Part Two official trailer",
    trailerVideoId: "U2Qp5pL3ovA",
    mood: "gritty",
    posterUrl: "/media/movies/dune-part-two.jpg",
  },
  {
    title: "Hit Man",
    year: "2024",
    type: "movie",
    description:
      "A fake contract killer leans too hard into his undercover personas and turns a sting operation into a flirtation.",
    genre: "Comedy Thriller",
    country: "USA",
    language: "English",
    streamingService: "Netflix",
    tmdbSearchTitle: "Hit Man",
    trailerSearchQuery: "Hit Man official trailer Netflix",
    trailerVideoId: "-6BnM4LZxH4",
    mood: "funny",
    posterUrl: "/media/movies/hit-man.jpg",
  },
  {
    title: "The Killer",
    year: "2023",
    type: "movie",
    description:
      "David Fincher turns an assassin's routine into a cold, precise spiral of paranoia and revenge.",
    genre: "Crime Thriller",
    country: "USA",
    language: "English",
    streamingService: "Netflix",
    tmdbSearchTitle: "The Killer",
    trailerSearchQuery: "The Killer 2023 official trailer Netflix",
    trailerVideoId: "5S7FR_HCg9g",
    mood: "suspenseful",
    posterUrl: "/media/movies/the-killer.jpg",
  },
  {
    title: "Society of the Snow",
    year: "2023",
    type: "movie",
    description:
      "A plane crash in the Andes becomes a brutal survival story where endurance, grief, and impossible choices collide.",
    genre: "Survival Drama",
    country: "Spain",
    language: "Spanish",
    streamingService: "Netflix",
    tmdbSearchTitle: "Society of the Snow",
    trailerSearchQuery: "Society of the Snow official trailer Netflix",
    trailerVideoId: "pDak4qLyF4Q",
    mood: "gritty",
    posterUrl: "/media/movies/society-of-the-snow.jpg",
  },
];
