import type { ShowItem } from "@/lib/shows-recommendations-grok";

export const CURATED_SHOWS_VERSION = 8;

export const CURATED_SHOWS: ShowItem[] = [
  {
    title: "The Pitt",
    year: "2025",
    type: "show",
    description:
      "A high-pressure emergency room turns every hour into a sprint, with sharp dialogue and relentless momentum.",
    genre: "Medical Drama",
    country: "USA",
    language: "English",
    streamingService: "Max",
    tmdbSearchTitle: "The Pitt",
    trailerSearchQuery: "The Pitt 2025 official trailer Max",
    trailerVideoId: null,
    mood: "gritty",
    posterUrl: null,
  },
  {
    title: "Adolescence",
    year: "2025",
    type: "show",
    description:
      "A family nightmare spirals into a tense crime story with raw performances and a steady sense of dread.",
    genre: "Crime Drama",
    country: "UK",
    language: "English",
    streamingService: "Netflix",
    tmdbSearchTitle: "Adolescence",
    trailerSearchQuery: "Adolescence 2025 official trailer Netflix",
    trailerVideoId: null,
    mood: "suspenseful",
    posterUrl: null,
  },
  {
    title: "Black Doves",
    year: "2025",
    type: "show",
    description:
      "A London spy thriller mixes betrayals, gunfire, and dark humor without ever slowing down.",
    genre: "Spy Thriller",
    country: "UK",
    language: "English",
    streamingService: "Netflix",
    tmdbSearchTitle: "Black Doves",
    trailerSearchQuery: "Black Doves 2025 official trailer Netflix",
    trailerVideoId: null,
    mood: "gritty",
    posterUrl: null,
  },
  {
    title: "Prime Target",
    year: "2025",
    type: "show",
    description:
      "Math, surveillance, and conspiracy collide in a sleek thriller that stays tense and cerebral.",
    genre: "Conspiracy Thriller",
    country: "UK",
    language: "English",
    streamingService: "Apple TV+",
    tmdbSearchTitle: "Prime Target",
    trailerSearchQuery: "Prime Target 2025 official trailer Apple TV",
    trailerVideoId: null,
    mood: "suspenseful",
    posterUrl: null,
  },
  {
    title: "Paradise",
    year: "2025",
    type: "show",
    description:
      "Power, paranoia, and buried secrets fuel a glossy political thriller with genuine bite.",
    genre: "Political Thriller",
    country: "USA",
    language: "English",
    streamingService: "Hulu",
    tmdbSearchTitle: "Paradise",
    trailerSearchQuery: "Paradise 2025 official trailer Hulu",
    trailerVideoId: null,
    mood: "gritty",
    posterUrl: null,
  },
  {
    title: "Dept. Q",
    year: "2025",
    type: "show",
    description:
      "A cold-case unit digs through ugly histories in a moody crime series with hard edges and dry wit.",
    genre: "Crime Thriller",
    country: "Denmark",
    language: "Danish",
    streamingService: "Netflix",
    tmdbSearchTitle: "Dept. Q",
    trailerSearchQuery: "Dept Q 2025 official trailer Netflix",
    trailerVideoId: null,
    mood: "gritty",
    posterUrl: null,
  },
  {
    title: "The Studio",
    year: "2025",
    type: "show",
    description:
      "Hollywood panic becomes rapid-fire comedy in a satire full of ego, absurdity, and beautifully timed chaos.",
    genre: "Comedy",
    country: "USA",
    language: "English",
    streamingService: "Apple TV+",
    tmdbSearchTitle: "The Studio",
    trailerSearchQuery: "The Studio 2025 official trailer Apple TV",
    trailerVideoId: null,
    mood: "funny",
    posterUrl: null,
  },
  {
    title: "Dope Thief",
    year: "2025",
    type: "show",
    description:
      "A small-time scam explodes into violence and pressure, giving this crime series a bruised, propulsive energy.",
    genre: "Crime Drama",
    country: "USA",
    language: "English",
    streamingService: "Apple TV+",
    tmdbSearchTitle: "Dope Thief",
    trailerSearchQuery: "Dope Thief 2025 official trailer Apple TV",
    trailerVideoId: null,
    mood: "gritty",
    posterUrl: null,
  },
  {
    title: "Zero Day",
    year: "2025",
    type: "show",
    description:
      "Cyber panic and political pressure drive a sharp, high-stakes thriller built around crisis management.",
    genre: "Political Thriller",
    country: "USA",
    language: "English",
    streamingService: "Netflix",
    tmdbSearchTitle: "Zero Day",
    trailerSearchQuery: "Zero Day 2025 official trailer Netflix",
    trailerVideoId: null,
    mood: "suspenseful",
    posterUrl: null,
  },
  {
    title: "The Residence",
    year: "2025",
    type: "show",
    description:
      "A murder mystery inside the White House turns eccentric characters and fast banter into pure fun.",
    genre: "Mystery Comedy",
    country: "USA",
    language: "English",
    streamingService: "Netflix",
    tmdbSearchTitle: "The Residence",
    trailerSearchQuery: "The Residence 2025 official trailer Netflix",
    trailerVideoId: null,
    mood: "quirky",
    posterUrl: null,
  },
];

export const CURATED_MOVIES: ShowItem[] = [
  {
    title: "Companion",
    year: "2025",
    type: "movie",
    description:
      "A sleek genre-bender turns a getaway into a vicious game of control, panic, and dark laughs.",
    genre: "Sci-Fi Thriller",
    country: "USA",
    language: "English",
    streamingService: "Max",
    tmdbSearchTitle: "Companion",
    trailerSearchQuery: "Companion 2025 official trailer",
    trailerVideoId: null,
    mood: "suspenseful",
    posterUrl: null,
  },
  {
    title: "The Gorge",
    year: "2025",
    type: "movie",
    description:
      "Action, romance, and monster-movie dread blend into a pulpy streaming thriller with real momentum.",
    genre: "Action Thriller",
    country: "USA",
    language: "English",
    streamingService: "Apple TV+",
    tmdbSearchTitle: "The Gorge",
    trailerSearchQuery: "The Gorge 2025 official trailer Apple TV",
    trailerVideoId: null,
    mood: "gritty",
    posterUrl: null,
  },
  {
    title: "Black Bag",
    year: "2025",
    type: "movie",
    description:
      "An elegant spy story keeps twisting loyalty, marriage, and deception into something nasty and smart.",
    genre: "Spy Thriller",
    country: "UK",
    language: "English",
    streamingService: "Peacock",
    tmdbSearchTitle: "Black Bag",
    trailerSearchQuery: "Black Bag 2025 official trailer",
    trailerVideoId: null,
    mood: "suspenseful",
    posterUrl: null,
  },
  {
    title: "Havoc",
    year: "2025",
    type: "movie",
    description:
      "A corrupt city, a desperate rescue, and brutal close-quarters action make this one pure grimy propulsion.",
    genre: "Action Crime",
    country: "USA",
    language: "English",
    streamingService: "Netflix",
    tmdbSearchTitle: "Havoc",
    trailerSearchQuery: "Havoc 2025 official trailer Netflix",
    trailerVideoId: null,
    mood: "gritty",
    posterUrl: null,
  },
  {
    title: "Holland",
    year: "2025",
    type: "movie",
    description:
      "A polished suburban mystery gradually peels back into something stranger, meaner, and more unstable.",
    genre: "Mystery Thriller",
    country: "USA",
    language: "English",
    streamingService: "Prime Video",
    tmdbSearchTitle: "Holland",
    trailerSearchQuery: "Holland 2025 official trailer Prime Video",
    trailerVideoId: null,
    mood: "quirky",
    posterUrl: null,
  },
  {
    title: "Drop",
    year: "2025",
    type: "movie",
    description:
      "A single night spirals into a compact suspense machine full of digital paranoia and escalating pressure.",
    genre: "Thriller",
    country: "USA",
    language: "English",
    streamingService: "Peacock",
    tmdbSearchTitle: "Drop",
    trailerSearchQuery: "Drop 2025 official trailer",
    trailerVideoId: null,
    mood: "suspenseful",
    posterUrl: null,
  },
  {
    title: "The Electric State",
    year: "2025",
    type: "movie",
    description:
      "A retro-futurist road movie turns weird robots and collapse-era landscapes into a big, moody streaming spectacle.",
    genre: "Sci-Fi Adventure",
    country: "USA",
    language: "English",
    streamingService: "Netflix",
    tmdbSearchTitle: "The Electric State",
    trailerSearchQuery: "The Electric State 2025 official trailer Netflix",
    trailerVideoId: null,
    mood: "fun",
    posterUrl: null,
  },
  {
    title: "The Parenting",
    year: "2025",
    type: "movie",
    description:
      "A haunted weekend and terrible family dynamics fuel a fast, mean little horror-comedy.",
    genre: "Horror Comedy",
    country: "USA",
    language: "English",
    streamingService: "Max",
    tmdbSearchTitle: "The Parenting",
    trailerSearchQuery: "The Parenting 2025 official trailer Max",
    trailerVideoId: null,
    mood: "funny",
    posterUrl: null,
  },
  {
    title: "Presence",
    year: "2025",
    type: "movie",
    description:
      "A haunted-house premise becomes an intimate, unnerving suspense piece with elegant formal control.",
    genre: "Psychological Thriller",
    country: "USA",
    language: "English",
    streamingService: "Hulu",
    tmdbSearchTitle: "Presence",
    trailerSearchQuery: "Presence 2025 official trailer",
    trailerVideoId: null,
    mood: "suspenseful",
    posterUrl: null,
  },
  {
    title: "Heart Eyes",
    year: "2025",
    type: "movie",
    description:
      "A slasher setup meets rom-com timing, turning date-night chaos into a fast and surprisingly funny horror ride.",
    genre: "Horror Comedy",
    country: "USA",
    language: "English",
    streamingService: "Netflix",
    tmdbSearchTitle: "Heart Eyes",
    trailerSearchQuery: "Heart Eyes 2025 official trailer",
    trailerVideoId: null,
    mood: "funny",
    posterUrl: null,
  },
];
